### ISSUE TITLE
Car is making funny turns in the simulator

### ISSUE THREAD

**Issue by michaelzhang917** [whats-in-a-name/CarND-Capstone#25]
**Steps to Reproduce**

Running self-driving in simulator

**Expected Behavior**

The car should be able to drive at least one full loop.

**Actual Behavior**

The car is always making funny turns at the same location as shown below.

![screenshot from 2017-09-26 18-01-41](https://user-images.githubusercontent.com/10564563/30922778-f78708c4-a35e-11e7-9b21-02c6f7c9af6d.png)

More on Youtube

https://youtu.be/OSvRl_uZ734

**Comment by xperroni** [comment]
After extended tests it was verified that the issue isn't actually solved yet.
