### ISSUE TITLE
Error starting Waypoint Updater

### ISSUE THREAD

**Issue by xperroni** [whats-in-a-name/CarND-Capstone#6]
Running node `waypoint_updater.py` fails with the following error message:

    /usr/bin/env: �python\r�: No such file or directory

**Comment by xperroni** [comment]
Fixed, see commit 455684a2b1199e7d7f2cd29eda40dbbc39878d37 for details.

**Comment by IanBoyanZhang** [comment]
Is this indentation issue? Thanks!

**Comment by xperroni** [comment]
It's an error in the way line breaks are encoded: in Windows line breaks are encoded as a Carriage Return character followed by a New Line (i.e. "\r\n"), while in Linux a lone New Line is used ("\n"). It's important to ensure text files use the Linux standard for line break encoding in order to avoid this kind of error.

**Comment by IanBoyanZhang** [comment]
Thanks, it totally makes sense!

**Comment by xperroni** [comment]
Why did you reopen the issue?

**Comment by xperroni** [comment]
Closing issue again after it was reopened without explanation (possibly a mistake)?

**Comment by IanBoyanZhang** [comment]
@xperroni Sorry, I reopen the issue by mistake.
